// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uukvbtbhphpruzcjvgol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1a3ZidGJocGhwcnV6Y2p2Z29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTQxOTEsImV4cCI6MjA1MTkzMDE5MX0.wDQwPz2ORli8PTne3Kau_nSPa3dJb7Q2W-2w1Pcr1N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);